Repository AY2021S1-CS2103T-T09-3/tp, pull requests merged in 2020-10, with the labels that each got.

#102 Branch v1.2 mark visited
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/attraction/Attraction.java
  src/main/java/seedu/address/model/attraction/Visited.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAttraction.java
  src/main/java/seedu/address/ui/AttractionCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableTrackPadTest/duplicateAttractionTrackPad.json
  src/test/data/JsonSerializableTrackPadTest/typicalAttractionsTrackPad.json
  src/test/data/JsonTrackPadStorageTest/invalidAndValidAttractionTrackPad.json
  src/test/data/JsonTrackPadStorageTest/invalidAttractionTrackPad.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/attraction/VisitedTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAttractionTest.java
  src/test/java/seedu/address/testutil/AttractionBuilder.java
  src/test/java/seedu/address/testutil/AttractionUtil.java
  src/test/java/seedu/address/testutil/EditAttractionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalAttractions.java
Labels: hacktoberfest-accepted

#103 Branch v1.2 Visited as red box
  src/main/java/seedu/address/ui/AttractionCard.java
  src/main/resources/view/DarkTheme.css
Labels: hacktoberfest-accepted

#150 Edit Add attraction under User Guide
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  src/main/java/seedu/address/model/attraction/Address.java
  src/main/java/seedu/address/model/attraction/Location.java
Labels: documentation

#152 Add edit command in User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/attraction/Address.java
Labels: documentation

#154 Update Dev Guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
Labels: documentation

#155 Add breakline between caption
  docs/DeveloperGuide.md
Labels: documentation

#153 Update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/findAlexDavidResult.png
  docs/images/findJurongResult.PNG
Labels: documentation

#156 Branch edit ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#157 Edit table of content
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#158 Edit table of contents to fix it
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#161 Update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#162 Edit UGDG
  docs/UserGuide.md
  docs/images/BetterModelClassDiagram.png
Labels: documentation

#163 Update Ui.png
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#164 Refine user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#171 Add new visited testcases
  docs/DeveloperGuide.md
  src/test/java/seedu/address/logic/commands/EditAttractionDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddAttractionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditAttractionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/attraction/AttractionTest.java
Labels: hacktoberfest-accepted

#172 Branchv1.3 Add test case for AddItineraryAttractionCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/DeleteItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/itineraryattraction/AddItineraryAttractionCommandParser.java
  src/main/java/seedu/address/logic/parser/itineraryattraction/DeleteItineraryAttractionCommandParser.java
  src/main/java/seedu/address/logic/parser/itineraryattraction/EditItineraryAttractionCommandParser.java
  src/main/java/seedu/address/model/itinerary/Itinerary.java
  src/main/java/seedu/address/model/itinerary/ItineraryAttraction.java
  src/main/java/seedu/address/model/itinerary/ItineraryTime.java
  src/main/java/seedu/address/storage/JsonAdaptedItineraryAttraction.java
  src/test/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommandTest.java
  src/test/java/seedu/address/testutil/ItineraryAttractionBuilder.java
Labels: testcases

#173 Branch edit ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ItineraryAttraction.pptx
  docs/images/ItineraryAttraction.png
Labels: documentation

#183 Branchv1.3 refine ug3
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addAttractionResult.png
  docs/images/deleteAttractionResult.png
  docs/images/editAttractionResult1.png
  docs/images/editAttractionResult2.png
  docs/images/findJurongResult.png
  docs/index.md
Labels: documentation

#186 Add prefaces to each section in UG(except features)
  docs/UserGuide.md
  docs/images/ItineraryAttraction.png
  docs/images/markVisitedAttraction.png
Labels: documentation

#197 Branchv1.3 test parser
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/DeleteItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/parser/itineraryattraction/EditItineraryAttractionCommandParser.java
  src/main/java/seedu/address/model/itinerary/ItineraryTime.java
  src/test/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/itineraryattraction/EditItineraryAttractionCommandParserTest.java
Labels: bug, testcases

#198 Update tests for itinerary, itinerary storage and itinerary command parsers
  src/main/java/seedu/address/model/itinerary/Day.java
  src/main/java/seedu/address/model/itinerary/Itinerary.java
  src/main/java/seedu/address/model/itinerary/ItineraryAttraction.java
  src/main/java/seedu/address/model/itinerary/ItineraryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/itinerary/ItineraryTime.java
  src/main/java/seedu/address/storage/JsonAdaptedItineraryAttraction.java
  src/main/java/seedu/address/ui/ItineraryListCard.java
  src/test/data/JsonSerializableTrackPadTest/duplicateItineraryTrackPad.json
  src/test/data/JsonSerializableTrackPadTest/invalidItineraryTrackPad.json
  src/test/data/JsonSerializableTrackPadTest/typicalAttractionsTrackPad.json
  src/test/data/JsonSerializableTrackPadTest/typicalItinerariesTrackPad.json
  src/test/data/JsonTrackPadStorageTest/invalidAndValidItineraryTrackPad.json
  src/test/data/JsonTrackPadStorageTest/invalidItineraryTrackPad.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/attraction/EditAttractionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/itinerary/AddItineraryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/itinerary/EditItineraryCommandParserTest.java
  src/test/java/seedu/address/model/attraction/AttractionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/attraction/AttractionTest.java
  src/test/java/seedu/address/model/attraction/UniqueAttractionListTest.java
  src/test/java/seedu/address/model/itinerary/ItineraryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/itinerary/ItineraryTest.java
  src/test/java/seedu/address/model/itinerary/UniqueItineraryListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedItineraryTest.java
  src/test/java/seedu/address/storage/JsonItineraryListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableItineraryListTest.java
  src/test/java/seedu/address/testutil/ItineraryListBuilder.java
  src/test/java/seedu/address/testutil/TypicalItineraries.java
Labels: testcases

#209 Update Ui.png in user guide
  docs/images/Ui.png
Labels: documentation

#212 Add itinerary pictures to ug
  docs/UserGuide.md
  docs/images/addItinerary.png
  docs/images/clearItinerary.png
  docs/images/deleteItinerary.png
  docs/images/editItinerary.png
  docs/images/findItinerary.png
  docs/images/listItinerary.png
  docs/images/selectItinerary.png
Labels: documentation

#213 Branch v1.3 userguide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation
