Repository AY2021S1-CS2103T-T09-3/tp, pull requests merged in 2020-11, with the labels that each got.

#269 Branchv1.4 bug fix
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/attraction/DeleteAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/EditAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/MarkVisitedAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/DeleteItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/EditItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/SelectItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/DeleteItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/itineraryattraction/AddItineraryAttractionCommandParser.java
  src/main/java/seedu/address/model/ItineraryList.java
  src/test/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommandTest.java
  src/test/java/seedu/address/logic/commands/itineraryattraction/DeleteItineraryAttractionCommandTest.java
  src/test/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommandTest.java
  src/test/java/seedu/address/logic/parser/TrackPadParserTest.java
  src/test/java/seedu/address/logic/parser/itineraryattraction/AddItineraryAttractionCommandParserTest.java
Labels: bug, documentation

#273 Tweaked UI
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/AddItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/ClearItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/DeleteItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/EditItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/FindItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/ListItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/SelectItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/DeleteItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: bug

#275 Fix text wraparound issue in UI
  docs/UserGuide.md
  src/main/java/seedu/address/ui/AttractionCard.java
  src/main/java/seedu/address/ui/ItineraryAttractionListCard.java
  src/main/java/seedu/address/ui/ItineraryListCard.java
Labels: UI

#280 PPP basic draft
  docs/AboutUs.md
  docs/team/Robinho98.md
Labels: documentation

#277 Add multiple fields message, itinerary fields table and PPP draft
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/limkoonkiat.jpg
  docs/images/limkoonkiat.png
  docs/team/limkoonkiat.md
Labels: documentation

#283 Branchv1.4 ppp
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/peteryeh.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/attraction/AddAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/DeleteAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/EditAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/FindAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/ListAttractionCommand.java
  src/main/java/seedu/address/logic/commands/attraction/MarkVisitedAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/AddItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/DeleteItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/EditItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/ListItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itinerary/SelectItineraryCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/AddItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/DeleteItineraryAttractionCommand.java
  src/main/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommand.java
  src/main/java/seedu/address/model/attraction/Address.java
  src/main/java/seedu/address/model/attraction/Location.java
  src/main/java/seedu/address/model/attraction/OpeningHours.java
  src/main/java/seedu/address/model/attraction/Phone.java
  src/main/java/seedu/address/model/attraction/PriceRange.java
  src/main/java/seedu/address/model/attraction/Rating.java
  src/main/java/seedu/address/model/attraction/Visited.java
  src/main/java/seedu/address/model/attraction/exceptions/DuplicateAttractionException.java
  src/main/java/seedu/address/model/commons/Description.java
  src/main/java/seedu/address/model/commons/Name.java
  src/main/java/seedu/address/model/itinerary/Budget.java
  src/main/java/seedu/address/model/itinerary/Day.java
  src/main/java/seedu/address/model/itinerary/Itinerary.java
  src/main/java/seedu/address/model/itinerary/ItineraryDate.java
  src/main/java/seedu/address/model/itinerary/ItineraryTime.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: documentation, enhancement

#294 Fix UG
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#307 Branchv1.4 user guide4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/itineraryattraction/EditItineraryAttractionCommandTest.java
Labels: documentation

#318 Branchv1.4 user guide5
  docs/User Guide Section 4.4 Itinerary Attraction.pptx
  docs/UserGuide.md
  docs/images/AddItineraryAttraction1.png
  docs/images/AddItineraryAttraction2.png
  docs/images/AddItineraryAttraction3.png
  docs/images/DeleteItineraryAttraction1.png
  docs/images/DeleteItineraryAttraction2.png
  docs/images/EditItineraryAttraction1.png
  docs/images/EditItineraryAttraction2.png
  docs/images/EditItineraryAttraction3.png
  docs/images/ItineraryAttraction.png
  docs/images/addItineraryAttraction.png
  docs/images/deleteItineraryAttraction.png
  docs/images/editItineraryAttraction.png
Labels: documentation, enhancement

#317 Branch v1.4 ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/Ui-Labelled.pptx
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/Ui-Labelled.png
  docs/images/gettingStartedAddAttraction.png
  docs/images/gettingStartedAddItinerary.png
  docs/images/gettingStartedAddItineraryAttraction.png
  docs/images/gettingStartedEditAttraction.png
  docs/images/gettingStartedSelectItinerary.png
  docs/team/leeyorktat.md
  docs/team/limkoonkiat.md
  docs/team/peter-yeh.md
  src/main/java/seedu/address/ui/ItineraryListCard1Field.java
  src/main/java/seedu/address/ui/ItineraryListCard2Field.java
Labels: documentation

#320 Branch v1.4 ugdg rearrange powerpoints
  docs/diagrams/ItineraryAttraction.pptx
  docs/images/userguideimages/Powerpoints/User Guide Section 3 Getting Started.pptx
  docs/images/userguideimages/Powerpoints/User Guide Section 4.4 Itinerary Attraction.pptx
  docs/images/userguideimages/Powerpoints/User Guide Ui-Labelled.pptx
Labels: documentation

#321 Branchv1.4 user guide7
  docs/UserGuide.md
Labels: documentation

#333 Branchv1.4 dev guide3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/github-icon.png
Labels: documentation

#338 Draft implementation and edits
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddItinerarySequenceDiagram.puml
  docs/diagrams/ItineraryClassDiagram.puml
  docs/images/devguideimages/AddItinerarySequenceDiagram.png
  docs/images/devguideimages/ItineraryClassDiagram.png
  docs/images/userguideimages/ItineraryCard.PNG
Labels: documentation

#339 Branchv1.4 dev guide4
  docs/DeveloperGuide.md
  docs/diagrams/AddItineraryAttractionActivityDiagram.puml
  docs/diagrams/AddItineraryAttractionSequenceDiagram.puml
  docs/diagrams/ItineraryAttractionClassDiagram.puml
  docs/images/devguideimages/AddItineraryAttractionActivityDiagram.png
  docs/images/devguideimages/AddItineraryAttractionSequenceDiagram.png
  docs/images/devguideimages/ItineraryAttractionClassDiagram.png
Labels: documentation

#346 Branchv1.4 dev guide5
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/userguideimages/EditItineraryAttraction1.png
  docs/images/userguideimages/EditItineraryAttraction2.png
  docs/images/userguideimages/EditItineraryAttraction3.png
  docs/images/userguideimages/Powerpoints/User Guide Section 4.4 Itinerary Attraction.pptx
Labels: documentation

#349 Add testcases and Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiFxml.puml
  docs/images/devguideimages/UiFxml.png
  docs/team/robinho98.md
  src/main/java/seedu/address/model/itinerary/ItineraryAttractionDayCounter.java
  src/main/java/seedu/address/model/itinerary/ItineraryAttractionIndexCounter.java
  src/main/java/seedu/address/ui/AttractionCard.java
  src/test/java/seedu/address/model/itinerary/ItineraryAttractionDayCounterTest.java
  src/test/java/seedu/address/model/itinerary/ItineraryAttractionIndexCounterTest.java
Labels: documentation

#351 Fix links in Section 3 Step 10
  docs/UserGuide.md
  docs/images/userguideimages/Powerpoints/User Guide Ui-Labelled.pptx
  docs/images/userguideimages/Ui-Labelled.png
Labels: documentation

#353 Refine user guide.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddItineraryAttractionSequenceDiagram.puml
  docs/diagrams/DeleteAttractionSequenceDiagram.puml
  docs/images/devguideimages/AddItineraryAttractionSequenceDiagram.png
  docs/images/devguideimages/DeleteAttractionSequenceDiagram.png
  docs/images/devguideimages/DeleteSequenceDiagram.png
  docs/images/userguideimages/AddItineraryAttraction2.png
  docs/images/userguideimages/DeleteItineraryAttraction1.png
  docs/images/userguideimages/EditItineraryAttraction2.png
  docs/images/userguideimages/Powerpoints/User Guide Section 4.4 Itinerary Attraction.pptx
Labels: documentation

#366 Updated UG and DG for final submission, including page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/userguideimages/Powerpoints/User Guide Section 3 Getting Started.pptx
  docs/images/userguideimages/gettingStartedAddItinerary.png
  docs/team/robinho98.md
Labels: documentation

#367 Refine PPP links and layout.
  docs/team/peter-yeh.md
Labels: documentation

#368 Branchv1.4 dev guide6
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/peter-yeh.md
Labels: documentation

#371 Branch v1.4 ugdg
  docs/UserGuide.md
Labels: documentation

#374 Minor update to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#377 Branch v1.4 ugdg
  docs/UserGuide.md
Labels: documentation

#380 Edit PPP
  docs/DeveloperGuide.md
  docs/team/robinho98.md
Labels: documentation

#381 Branchv1.4 ug3
  docs/UserGuide.md
  docs/images/devguideimages/CommitActivityDiagram.png
  docs/images/devguideimages/LogicStorageDIP.png
  docs/images/devguideimages/UndoRedoState0.png
  docs/images/devguideimages/UndoRedoState1.png
  docs/images/devguideimages/UndoRedoState2.png
  docs/images/devguideimages/UndoRedoState3.png
  docs/images/devguideimages/UndoRedoState4.png
  docs/images/devguideimages/UndoRedoState5.png
  docs/images/devguideimages/UndoSequenceDiagram.png
  docs/images/devguideimages/request_access.png
Labels: documentation

#386 Branch v1.4 ugdg
  docs/DeveloperGuide.md
Labels: documentation

#391 Refine DG.
  docs/DeveloperGuide.md
Labels: documentation

#393 Fix broken table.
  docs/DeveloperGuide.md
Labels: documentation

#395 Refine DG.
  docs/DeveloperGuide.md
Labels: documentation

#396 Rewrite last paragraph for effort
  docs/DeveloperGuide.md
Labels: documentation

#397 Minor change to DG
  docs/DeveloperGuide.md
Labels: documentation

#398 Minor change to DG
  docs/DeveloperGuide.md
Labels: documentation
